[package]
name = "gui_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
rand = "0.8"
lazy_static = "1.4.0"
mc-query = "1.0.1"
tokio = "=1.38.0"